# Generated by Django 4.2 on 2025-05-17 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contact_doc/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docs', 'docx', 'txt'])]),
        ),
    ]
